### ISSUE TITLE
Getting draft events via master branch

### ISSUE THREAD

**Issue by sigdestad** [enonic/lib-guillotine#160]
Using subscriptions, I'm getting events from draft branch, even when connected to master branch.

![Screenshot 2021-05-07 at 12 50 37](https://user-images.githubusercontent.com/482228/117439448-22fb0080-af33-11eb-9273-a8a96b48fded.png)

**Comment by anatol-sialitski** [comment]
@sigdestad Do you use some custom configuration for `subscriptionEventTypes`?

**Comment by anatol-sialitski** [comment]
I've reproduce it too. The reason is lib-context returns  the draft branch all time. I will figure out how to fix it.

**Comment by anatol-sialitski** [comment]
this bug was fixed in scope https://github.com/enonic/lib-guillotine/issues/166 issue.
