### ISSUE TITLE
Should events contain "distributed" field?

### ISSUE THREAD

**Issue by sigdestad** [enonic/lib-guillotine#161]
There is no obvious reason for why XP internals should be exposed via GraphQL API imho?

**Comment by rymsha** [comment]
Strictly speaking tnis field is parto of our event-api. it is not internal and allows developers to control (and read) scope of events.
It should remain in guillotine for completeness.

**Comment by anatol-sialitski** [comment]
@sigdestad any comments?

**Comment by sigdestad** [comment]
If Sergey says its ok, then its ok :-)
