### ISSUE TITLE
support easy trimming of _path via guillotine API

### ISSUE THREAD

**Issue by sigdestad** [enonic/lib-guillotine#192]
In some cases, users want to generate Url's directly from _path value of that item, however, this involves trimming away the path to the site in the client. The location of the site, is not always obvious - as such automating this would help.

I.e. content has path "/hmdb/persons/brad-pit" as the standard value, but the front-end developer just needs a site-relative path i.e. "/persons/brad-pit" 

suggested solution:  - add new parameter to the _path field "type: siteRelative" that automatically trunkates the content path.

Examples:

content path: /folder/other/mysite/path/to/content -> /path/to/content
content path: /hmdb/persons/brad-pitt -> /persons/brad-pitt

**Comment by espen42** [comment]
Is it an option to get `path/to/content` instead of `/path/to/content`?

NextJs needs both, and it's 10% easier to add a slash than to strip one away.

**Comment by sigdestad** [comment]
AFAIK: To remove the first character from any string must be one of the simplest possible things to do in just about any programming language? This should not be done in Guillotine imho.

**Comment by espen42** [comment]
> AFAIK: To remove the first character from any string must be one of the simplest possible things to do in just about any programming language? This should not be done in Guillotine imho.

If the first slash is stripped by guillotine, we can probably do without adding props postprocessing functions to the type rendering in nextjs. Not a huge deal, but that would simplify the guide and demo a bit.

Stripping the slash in next without a props postprocessor would be... hmm, I'm not sure if there's any good way to do that, but I'll think about it.

**Comment by sigdestad** [comment]
@anatol-sialitski - I propose the following adjustment to the task:

Let's support two types:
"siteRelative" returns the relative path **without** initial '/' i.e. my-content/path
"site" returns same response but with initial '/' i.e. /my-content/path

**Comment by espen42** [comment]
> @anatol-sialitski - I propose the following adjustment to the task:
> 
> Let's support two types: "siteRelative" returns the relative path **without** initial '/' i.e. my-content/path "site" returns same response but with initial '/' i.e. /my-content/path

An option like that to keep or remove the slash would be absoultely ideal for the nextjs project! :)

**Comment by rymsha** [comment]
Please don't do it. API should not do it.
site and siteRelative will be too confusing

It must be either with or without /
User code must be either always adding / (when needed) or always substucting /

I prefer to have / - it is consistent with what we have anywhere else

**Comment by anatol-sialitski** [comment]
Hi @sigdestad! What do you think about the last @rymsha's comment?

As alternative, we can use `siteRelative` and add the `withInitialSlash` flag as boolean, where `withInitialSlash` by default `false`.

**Comment by rymsha** [comment]
@anatol-sialitski `withInitialSlash` is even worse.

@espen42 what is props postprocessor in next.js and why is it such a big deal?
Ah, 
> Not a huge deal

It is not. So, case closed then ?

**Comment by rymsha** [comment]
Usually site is a target path for a vhost, so path is essentially a content-path. (BTW, it starts with /)
So, we are tuning in a feature for a very specific use-case - to "mimic" usual vhost configuration.

We do also, internally in XP, have _siteRelative_ content path, but ONLY for one specific feature: controller/filter mappings whose Path Patterns are Site relative - and they are always prepended with `/`.

**Comment by anatol-sialitski** [comment]
After discussion we decided that the `_path` field will support the optional  `type` argument with `siteRelative` value. It means that path returns the relative path without initial '/' i.e. `my-content/path`.
