### ISSUE TITLE
Add the `site` value to ContentPathType

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/lib-guillotine#203]
https://github.com/enonic/lib-guillotine/issues/192#issuecomment-983521723
Add the `site` value to `ContentPathType`.

After that `ContentPathType` supports two options:

- `siteRelative` returns the relative path without initial '/' i.e. `my-content/path`
- `site` returns same response but with initial '/' i.e. `/my-content/path`

**Comment by rymsha** [comment]
I have written my concerns about "site" ConttentPathType [here](https://github.com/enonic/lib-guillotine/issues/192#issuecomment-983547521)

All graphql client libraries support schema [transformation](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#the-read-function). So there is no need to complicate our API with trivial transformations

**Comment by sigdestad** [comment]
Is schema Transformation equivalent to data Transformation?

**Comment by rymsha** [comment]
Yes:

> Other use cases for a read function include:
> - Transforming cached data to suit your client's needs, such as rounding floating-point values to the nearest integer
> - Deriving local-only fields from one or more schema fields on the same object (such as deriving an age field from a birthDate field)
> - Deriving local-only fields from one or more schema fields across multiple objects

**Comment by sigdestad** [comment]
Beautiful.

**Comment by anatol-sialitski** [comment]
Maybe in this case we can get rid of the `type` argument in the `_path` field?

**Comment by rymsha** [comment]
I'd keep some room for improvement, if we already have it. Just in case.
