### ISSUE TITLE
Siteless improvements

### ISSUE THREAD

**Issue by rymsha** [enonic/lib-guillotine#225]
- [x] in-siteless mode pageUrl should point to content as repository root is a site (don't forget vhost rewriting)
- [x] in-siteless mode processHtml should generate links as they are based from repository root is a site (don't forget vhost rewriting)
- [x] in `admin` mode `/admin/site/preview/` should be be used as a base for links (don't forget vhost rewriting)
- [x] permissions to access the GraphiQL UI tab (system.admin + cms.admin)
- [ ] ~in GraphiQL UI show a toast than schema was changed with a link to refresh the page~ moved to https://github.com/enonic/app-guillotine/issues/118
- [x] support wss protocol in app-guillotine (via portalLib.url)
- [x] automatic recognition of mode: project/site

**Comment by sigdestad** [comment]
I don't see why pageUrl should be "null" - how about returning content://id?, same for htmlarea?

We need a chat about this...
