### ISSUE TITLE
ProcessHtml does not process image styles for Global API 

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/lib-guillotine#252]
ProcessHtml does not process image styles for Global API

**Comment by sigdestad** [comment]
Sample styles:



<styles>
  <image name="conteditor-style-grayscale">
    <display-name>Grayscale</display-name>
    <aspect-ratio>1:1</aspect-ratio> (1)
    <filter>hsbcolorize(0x000000); grayscale(); border(6, 0x000000)</filter> (2)
  </image>
</styles>
