### ISSUE TITLE
Guillotine 3 - Flattened components

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/lib-guillotine#27]
Add a field "components" on Content, returning a list of flattened components, similar to the structure of the serialization of page
(For help: https://github.com/enonic/xp/issues/6653#issuecomment-442489150)

**Comment by GlennRicaud** [comment]
![_Blank UML](https://user-images.githubusercontent.com/12030113/70711990-1beea500-1ce3-11ea-874b-7ddd990a58fd.png)

**Comment by GlennRicaud** [comment]
EDIT: Do not do sub types of FlatComponent. It will make its usage more complex in GraphQL.
We already are sure that there will not be any conflict.
![_Blank UML (2)](https://user-images.githubusercontent.com/12030113/70715964-aa672480-1ceb-11ea-970e-d10b8fd9bb12.png)

**Comment by sigdestad** [comment]
Sweet
