### ISSUE TITLE
Support custom processors for htmlArea

### ISSUE THREAD

**Issue by sigdestad** [enonic/lib-guillotine#40]
Every now and then, different customers may be looking to return special processed html before it is returned to the client. I.e. returning a markdown format, or other custom format (presumably all text-based?)

Suggest solutions to support alternative serverside processing of htmlArea inputs than the current solution. It should be possible to manipulate the deployment of lib-guillotine in a way that enables custom processing of html-area.

Propose a design solution that is flexible, and implement accordingly.

**Comment by GlennRicaud** [comment]
This is already doable by modifying the default schema when using the library.
I put this issue in backlog

**Comment by sigdestad** [comment]
Can be solves using creationCallbacks and the lib-guillotine
