### ISSUE TITLE
Confirm handling of _ and - in property names

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/lib-guillotine#73]
GraphQL does not support - characters in field names, but XP does. To mitigate this we currently replace - with _. However, if a field my-field and my_field exists at the same level, we would get a conflict.

Confirm that this is the current behaviour, and if there are any alternative ways of handling - names safely?

Guilltine 4:
field_name -> field_name (was broken for item/optionset and fixed recently)
field-name -> field_name 
fieldname -> fieldname
fieldName -> fieldName

Also, what other characters will be problematic for Guillotine? I.e. cyrillics, øæå etc? 
What is allowed and not in node layer?
What is documented?
Should we restrict something in content API?
Should there be options to specify guillotine

**Comment by anatol-sialitski** [comment]
In general transformation of field names  has the following behaviour:
```
field-name -> field_name
field_name -> field_name
fieldName -> fieldName
fieldname -> fieldname
```

But for a `option` tag under `option-set`, `items` tag and `input`s under `item-set` tag:
```
field-name -> fieldName
field_name -> fieldName
fieldName -> fieldName
```

If on the same level there are the following fields:

```
<input name="field_name" type="TextLine">
  <label>Field_Name</label>
  <occurrences maximum="1" minimum="0"/>
</input>
<input name="field-name" type="HtmlArea">
  <label>Field-Name</label>
  <custom-text>text</custom-text>
  <occurrences maximum="1" minimum="0"/>
</input>
```

then in a result will be present only the last field, because both have the same name `field_name` after processing.

**Comment by anatol-sialitski** [comment]
@sigdestad and @alansemenov please have a look at the result of research

**Comment by sigdestad** [comment]
So, are you saying itemset and optionset behave differently from regular fields?

**Comment by anatol-sialitski** [comment]
Yes, right.

**Comment by sigdestad** [comment]
It is a bit unclear for me. Can you create an example including "sets" and fields and show how the naming mapping is handled for them together?

**Comment by anatol-sialitski** [comment]
For the content type with the following definition:
```
<content-type>
  <display-name>MyContentType</display-name>
  <super-type>base:structured</super-type>
  <is-abstract>false</is-abstract>
  <is-final>true</is-final>
  <allow-child-content>true</allow-child-content>
  <form>
    <input type="TextLine" name="form_field_name_1">
      <label>form_field_name_1</label>
      <occurrences minimum="0" maximum="0"/>
    </input>
    <input type="TextLine" name="form_field-name-2">
      <label>form_field-name-2</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
    <input type="TextLine" name="form_fieldname">
      <label>form_fieldname</label>
      <occurrences maximum="1" minimum="0"/>
    </input>
    <input type="HtmTextLinelArea" name="form_fieldName">
      <label>form_fieldName</label>
      <custom-text>text</custom-text>
      <occurrences maximum="1" minimum="0"/>
    </input>
    <item-set name="item-set">
      <label>Item Set</label>
      <occurrences maximum="0" minimum="0"/>
      <items>
        <input type="TextLine" name="item-set_field_name_1">
          <label>item-set_field_name_1</label>
          <occurrences minimum="0" maximum="0"/>
        </input>
        <input type="TextLine" name="item-set_field-name-2">
          <label>item-set_field-name-2</label>
          <occurrences minimum="1" maximum="1"/>
        </input>
        <input type="TextLine" name="item-set_fieldname">
          <label>item-set_fieldname</label>
          <occurrences maximum="1" minimum="0"/>
        </input>
        <input type="TextLine" name="item-set_fieldName">
          <label>item-set_fieldName</label>
          <occurrences maximum="1" minimum="0"/>
        </input>
      </items>
    </item-set>
  </form>
</content-type>

```

will be generated the following fields:

![image](https://user-images.githubusercontent.com/53557255/102616173-335b3c00-4148-11eb-9884-5d459ed53134.png)

**Comment by sigdestad** [comment]
Ahh.. we definetly need to make this consistent. I guess we have two options:
a) Always do like inside sets (no underscores)
b) Same as outside sets (- becomes _) and we keep _
c) a bit of both, keep _ and kapitalcase items with -

What do you think?

Personally, I think c) feels like a nice compromise

**Comment by sigdestad** [comment]
Did you check out how we handle page components? I.e. parts and fields inside their config?

**Comment by anatol-sialitski** [comment]
For page/part/layout components the following behavior:
```
namingLib.sanitizeText(formItem.name)

field_name -> field_name
field-name -> field_name
fieldName -> fieldName
fieldname -> fieldname
```

![image](https://user-images.githubusercontent.com/53557255/104464459-ff96f900-55c3-11eb-908f-8f9f87378984.png)

**Comment by anatol-sialitski** [comment]
field_name -> field_name
field-name -> field_name
fieldName -> fieldName
fieldname -> fieldname
1fieldName -> _1fieldName
назаниеПоля -> nazaniepolja

Transliteration -> sinitize

**Comment by anatol-sialitski** [comment]
More examples

```
field+name -> field_name
field name -> field_name
field_name -> field_name
field-name -> field_name
field_Name -> field_Name
field-Name -> field_Name
fieldName -> fieldName
fieldname -> fieldname
123fieldName -> _123fieldName
fieldName123 -> fieldName123
fieldName-123 -> fieldName_123
fieldName_123 -> fieldName_123
fieldName 123 -> fieldName_123
названиеПолЯ -> nazvaniePolJA
#12названиеПоля?&*^% -> _12nazvaniePolja
 ```
